declare module '@ckeditor/ckeditor5-vue2'
declare module '@ckeditor/ckeditor5-utils';
declare module '@ckeditor/ckeditor5-vue'
declare module '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
declare module '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
declare module '@ckeditor/ckeditor5-list/src/list';
declare module '@ckeditor/ckeditor5-list/src/listproperties';
declare module '@ckeditor/ckeditor5-alignment/src/alignment';
declare module '@ckeditor/ckeditor5-basic-styles/src/code';
declare module '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
declare module '@ckeditor/ckeditor5-basic-styles/src/subscript';
declare module '@ckeditor/ckeditor5-basic-styles/src/superscript';
declare module '@ckeditor/ckeditor5-basic-styles/src/underline';
declare module '@ckeditor/ckeditor5-font/src/font';
declare module '@ckeditor/ckeditor5-font/src/fontfamily';
declare module '@ckeditor/ckeditor5-font/src/fontsize';
declare module '@ckeditor/ckeditor5-font/src/fontcolor';
declare module '@ckeditor/ckeditor5-font/src/fontbackgroundcolor';
declare module '@ckeditor/ckeditor5-horizontal-line/src/horizontalline';
declare module '@ckeditor/ckeditor5-indent/src/indent';
declare module '@ckeditor/ckeditor5-indent/src/indentblock';
declare module '@ckeditor/ckeditor5-image/src/imageresize';
declare module '@ckeditor/ckeditor5-table/src/tableproperties';
declare module '@ckeditor/ckeditor5-table/src/tablecellproperties';
declare module '@ckeditor/ckeditor5-build-classic/src/ckeditor';
declare module '@ckeditor/ckeditor5-build-classic';
declare module '@ckeditor/ckeditor5-essentials/src/essentials';
declare module '@ckeditor/ckeditor5-basic-styles/src/bold';
declare module '@ckeditor/ckeditor5-basic-styles/src/italic';
declare module '@ckeditor/ckeditor5-link/src/link';
declare module '@ckeditor/ckeditor5-paragraph/src/paragraph'
declare module '@ckeditor/ckeditor5-image/src/image'
declare module '@ckeditor/ckeditor5-image/src/imageupload';
declare module '@ckeditor/ckeditor5-image/src/imagetoolbar';
declare module '@ckeditor/ckeditor5-image/src/imagestyle';
declare module '@ckeditor/ckeditor5-image/src/imagecaption';
declare module '@ckeditor/ckeditor5-image/src/autoimage';
declare module '@ckeditor/ckeditor5-code-block/src/codeblock'
declare module '@ckeditor/ckeditor5-clipboard/src/clipboard';
declare module '@ckeditor/ckeditor5-clipboard/src/clipboardpipeline';
declare module '@ckeditor/ckeditor5-paragraph/src/paragraphbuttonui';
declare module '@ckeditor/ckeditor5-table/src/table';
declare module '@ckeditor/ckeditor5-table/src/tableclipboard';
declare module '@ckeditor/ckeditor5-table/src/tabletoolbar';
declare module '@ckeditor/ckeditor5-table/src/tablecaption';
declare module '@ckeditor/ckeditor5-table/src/tablecolumnresize';
declare module '@ckeditor/ckeditor5-heading/src/heading';
declare module '@ckeditor/ckeditor5-source-editing/src/sourceediting'
declare module '@ckeditor/ckeditor5-html-support/src/generalhtmlsupport'
declare module '@ckeditor/ckeditor5-inspector'
declare module '@ckeditor/ckeditor5-clipboard/src/dragdrop'
declare module '@/components/JournalComponents/EntryCellComponents/WYSIWYGCell/FlairPlugin/FlairPlugin'
declare module '@/components/JournalComponents/EntryCellComponents/WYSIWYGCell/EditorSavePlugin'
declare module '@/components/JournalComponents/EntryCellComponents/WYSIWYGCell/EditorCancelPlugin'
declare module '@/components/JournalComponents/EntryCellComponents/WYSIWYGCell/fileUploadPlugin/uploadPlugin'
declare module '@/components/JournalComponents/EntryCellComponents/WYSIWYGCell/fileUploadPlugin/imageUploadPlugin'
declare module '@ckeditor/ckeditor5-upload/src/filerepository'
declare module '@ckeditor/ckeditor5-upload/src/adapters/base64uploadadapter'
